Archive - archive experiments so they don't come back from the dead [¬º-°]¬
XPRMNTL/xpr-dashboard pull request #11
Opened 2017-06-09 16:59 UTC by spacerockzero

See: https://cloudup.com/cSJdpIPJ-m9

NOTE: Requires the xprmntl-dash-mongodb PR merged as well, since there is a schema change

2017-06-09 20:12 UTC, dncrews requested changes

2017-06-09 20:12 UTC, dncrews commented on assets/css/feature.css
> +  background-color: rgba(1,1,1,0.1);
?

2017-06-09 20:12 UTC, dncrews commented on package.json
> +    "xpr-dash-mongodb": "git+https://github.com/fs-webdev/xpr-dash-mongodb.git#archive",
Hold on this

2017-06-12 17:05 UTC, dncrews requested changes

2017-06-12 17:05 UTC, dncrews commented on assets/css/feature.styl
> +  background-color rgba(1,1,1,0.1)
?

2017-06-12 17:05 UTC, dncrews commented on assets/css/feature.styl
> +    border 2px dashed rgba(255,255,255,1)
?

2017-06-13 16:23 UTC, spacerockzero commented
@dncrews I've fixed the issues you mentioned.

2017-06-14 15:58 UTC, dncrews approved these changes

2017-06-14 15:58 UTC, merged

2017-06-14 17:37 UTC, spacerockzero commented
woot!